// Generated by scripts/method-compatibility.mjs; edit method/tools/harness/render-milestone-status.ts.
export * from '../../../method/tools/harness/render-milestone-status.ts';
import { main } from '../../../method/tools/harness/render-milestone-status.ts';

if (import.meta.main) await main();
