// Generated by scripts/method-compatibility.mjs; edit method/tools/harness/validate-milestone-cluster.ts.
export * from '../../../method/tools/harness/validate-milestone-cluster.ts';
import { main } from '../../../method/tools/harness/validate-milestone-cluster.ts';

if (import.meta.main) await main();
