/**
 * Installing the skill next to the labels it describes.
 *
 * Two things this does not do. It does not pick a location: it writes to whichever skill
 * directories the repository already has, and only falls back to a default when there are none, so
 * a repo that has settled on `.agents/skills` does not silently grow a second convention. And it
 * does not overwrite a file a human has edited — a generated skill that eats hand-written process
 * notes is a tool people stop running.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, posix } from "node:path";

import { renderSkill, type SkillContext } from "./render.js";

/** Where the skill goes when the repository has no skills directory yet. */
export const DEFAULT_SKILL_ROOT = ".claude/skills";
export const SKILL_NAME = "board-process";

/** Marks a file as ours, so a later run can tell its own output from someone's edits. */
const PROVENANCE = "<!-- generated by: dsh-forge skill install -->";

export type InstallOutcome =
  | "created"
  | "updated"
  /** Byte-identical to what we would write; nothing to do. */
  | "unchanged"
  /** Present, ours, but the operator did not pass --force and content differs. */
  | "stale"
  /** Present and not ours. Never touched without --force. */
  | "foreign";

export interface InstallReport {
  readonly path: string;
  readonly outcome: InstallOutcome;
  readonly note?: string;
}

export interface InstallOptions extends SkillContext {
  readonly repoRoot: string;
  /** Skill roots to install into, from detection. Empty means use {@link DEFAULT_SKILL_ROOT}. */
  readonly skillDirs: readonly string[];
  /** Overwrite content we did not generate, and refresh stale generated files. */
  readonly force?: boolean;
  /** Report what would happen without writing. */
  readonly dryRun?: boolean;
}

const readOrNull = async (path: string): Promise<string | null> => {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
};

export async function installSkill(options: InstallOptions): Promise<readonly InstallReport[]> {
  const roots = options.skillDirs.length > 0 ? options.skillDirs : [DEFAULT_SKILL_ROOT];
  const body = `${PROVENANCE}\n${renderSkill(options)}`;
  const reports: InstallReport[] = [];

  for (const root of roots) {
    // Reported with forward slashes on every platform: these paths end up in commit messages and
    // docs, where a Windows-shaped separator is noise.
    const relative = posix.join(root, SKILL_NAME, "SKILL.md");
    const path = join(options.repoRoot, relative);
    const existing = await readOrNull(path);

    if (existing === null) {
      if (!options.dryRun) {
        await mkdir(dirname(path), { recursive: true });
        await writeFile(path, body, "utf8");
      }
      reports.push({ path: relative, outcome: "created" });
      continue;
    }

    if (existing === body) {
      reports.push({ path: relative, outcome: "unchanged" });
      continue;
    }

    // Refreshing our own output is not clobbering; replacing someone else's file is, and needs
    // --force. That is the whole distinction the provenance marker exists to make.
    const ours = existing.includes(PROVENANCE);
    if (!ours && !options.force) {
      reports.push({
        path: relative,
        outcome: "foreign",
        note: "not generated by this tool — rerun with --force to replace it",
      });
      continue;
    }

    if (options.dryRun) {
      reports.push({
        path: relative,
        outcome: ours ? "stale" : "foreign",
        note: ours ? "would be refreshed" : "would be replaced (--force)",
      });
      continue;
    }

    await writeFile(path, body, "utf8");
    reports.push({
      path: relative,
      outcome: "updated",
      ...(ours ? {} : { note: "replaced a file this tool did not generate" }),
    });
  }

  return reports;
}
