import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";

import { DEFAULT_SKILL_ROOT, SKILL_NAME, installSkill } from "./install.js";
import { renderSkill } from "./render.js";
import { CORE_TAXONOMY, areaLabel, laneLabel } from "../labels/taxonomy.js";

const ctx = {
  repo: "owner/repo",
  specs: [...CORE_TAXONOMY, areaLabel("forge", "packages/forge")],
  lanePrefix: "topic",
};

const withTempRepo = async (fn: (root: string) => Promise<void>): Promise<void> => {
  const root = await mkdtemp(join(tmpdir(), "dsh-forge-skill-"));
  try {
    await fn(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
};

const skillPath = (root: string, dir: string) => join(root, dir, SKILL_NAME, "SKILL.md");

describe("renderSkill", () => {
  it("names only labels the repository actually has", () => {
    const text = renderSkill(ctx);
    assert.match(text, /`area:` — `forge`/);
    assert.ok(!text.includes("gate:"), "proposed a gate family the repo has none of");
    assert.ok(!text.includes("epic:"), "proposed an epic family the repo has none of");
  });

  it("teaches the lane prefix the repository uses, not the default", () => {
    const text = renderSkill({ ...ctx, specs: [...ctx.specs, laneLabel("docs", "topic", "docs")] });
    assert.match(text, /`topic:` — `docs`/);
    assert.ok(!text.includes("`lane:`"));
  });

  it("carries the two rules that make the taxonomy work", () => {
    const text = renderSkill(ctx);
    assert.match(text, /Exactly one `status:` label/);
    assert.match(text, /Closes #<n>/);
  });

  it("opens with usable skill frontmatter", () => {
    const text = renderSkill(ctx);
    assert.ok(text.startsWith("---\nname: board-process\n"));
    assert.match(text, /^description: >-$/m);
  });

  it("says nothing about dispatch in a repository that does not dispatch", () => {
    // The default. Warning about a trigger that does not exist teaches an agent to be careful of
    // nothing, and every sentence in a skill is one an agent has to read before it can start.
    for (const over of [{}, { dispatchLabel: null }]) {
      const text = renderSkill({ ...ctx, ...over });
      assert.ok(!text.includes("Dispatching a run"), JSON.stringify(over));
    }
  });

  it("warns about the label that starts a run, by its real name", () => {
    const text = renderSkill({ ...ctx, dispatchLabel: "harness" });
    assert.match(text, /## Dispatching a run/);
    assert.match(text, /`harness` is not a tag, it is a trigger/);
    assert.match(text, /No fenced code blocks/);
  });

  it("tells an agent what to do when the thing blocking it is a person", () => {
    // The flag only works if the agent that stops applies it. Nothing else in the run is in a
    // position to know that the reason it stopped was a decision rather than a failure.
    const text = renderSkill(ctx);
    assert.match(text, /## When the next move is not yours/);
    assert.match(text, /`flag:owner-decision`/);
    assert.match(text, /Leave the `status:` label exactly where it is/);
  });

  it("draws the line at things that already have a runner", () => {
    // Applied to a red build or an open review, the flag stops being a list of what a person owes
    // and becomes a second copy of the board — which is the thing that gets a list ignored.
    assert.match(renderSkill(ctx), /Not for a red build, a dependency, or a review/);
  });

  it("says nothing about the flag in a repository that does not have it", () => {
    const text = renderSkill({ ...ctx, specs: ctx.specs.filter((s) => s.name !== "flag:owner-decision") });
    assert.ok(!text.includes("When the next move is not yours"));
    assert.ok(!text.includes("owner-decision"), "naming a missing label teaches an agent to invent it");
  });

  it("puts the dispatch rules where they are read before the label goes on", () => {
    // Ordering is the whole point of the section: an agent that meets it after the instructions for
    // advancing a phase has already written the body it was supposed to write differently.
    const text = renderSkill({ ...ctx, dispatchLabel: "harness" });
    assert.ok(
      text.indexOf("## Dispatching a run") < text.indexOf("## When you advance a phase"),
      "dispatch guidance came after the phase instructions",
    );
  });
});

describe("installSkill", () => {
  it("creates the skill in the directory the repository already uses", async () => {
    await withTempRepo(async (root) => {
      await mkdir(join(root, ".agents", "skills"), { recursive: true });
      const reports = await installSkill({ ...ctx, repoRoot: root, skillDirs: [".agents/skills"] });

      assert.deepEqual(reports.map((r) => r.outcome), ["created"]);
      const written = await readFile(skillPath(root, ".agents/skills"), "utf8");
      assert.match(written, /generated by: dsh-forge skill install/);
      assert.match(written, /name: board-process/);
    });
  });

  it("falls back to .claude/skills only when the repo has none", async () => {
    await withTempRepo(async (root) => {
      const reports = await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      // Reported with forward slashes regardless of platform — these paths get pasted into docs.
      assert.equal(reports[0]?.path, `${DEFAULT_SKILL_ROOT}/${SKILL_NAME}/SKILL.md`);
      await readFile(skillPath(root, DEFAULT_SKILL_ROOT), "utf8");
    });
  });

  it("is idempotent — a second run reports unchanged", async () => {
    await withTempRepo(async (root) => {
      await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      const again = await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      assert.deepEqual(again.map((r) => r.outcome), ["unchanged"]);
    });
  });

  it("refreshes its own stale output without being asked twice", async () => {
    await withTempRepo(async (root) => {
      await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      const path = skillPath(root, DEFAULT_SKILL_ROOT);
      const stale = (await readFile(path, "utf8")).replace("Board process", "Board process (old)");
      await writeFile(path, stale, "utf8");

      const reports = await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      assert.deepEqual(reports.map((r) => r.outcome), ["updated"]);
      assert.ok(!(await readFile(path, "utf8")).includes("(old)"));
    });
  });

  it("will not eat a hand-written file without --force", async () => {
    await withTempRepo(async (root) => {
      const path = skillPath(root, DEFAULT_SKILL_ROOT);
      await mkdir(join(root, DEFAULT_SKILL_ROOT, SKILL_NAME), { recursive: true });
      await writeFile(path, "# our own process notes\n", "utf8");

      const reports = await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      assert.deepEqual(reports.map((r) => r.outcome), ["foreign"]);
      assert.equal(await readFile(path, "utf8"), "# our own process notes\n");

      const forced = await installSkill({ ...ctx, repoRoot: root, skillDirs: [], force: true });
      assert.deepEqual(forced.map((r) => r.outcome), ["updated"]);
      assert.match(await readFile(path, "utf8"), /name: board-process/);
    });
  });

  it("writes nothing under --dry-run", async () => {
    await withTempRepo(async (root) => {
      const reports = await installSkill({ ...ctx, repoRoot: root, skillDirs: [], dryRun: true });
      assert.deepEqual(reports.map((r) => r.outcome), ["created"]);
      await assert.rejects(readFile(skillPath(root, DEFAULT_SKILL_ROOT), "utf8"));
    });
  });

  it("installs into every skill directory the repo uses", async () => {
    await withTempRepo(async (root) => {
      const reports = await installSkill({
        ...ctx,
        repoRoot: root,
        skillDirs: [".claude/skills", ".agents/skills"],
      });
      assert.equal(reports.length, 2);
      for (const dir of [".claude/skills", ".agents/skills"]) {
        await readFile(skillPath(root, dir), "utf8");
      }
    });
  });
});

describe("the file that actually lands on disk", () => {
  // Every test above this block asserted on what `renderSkill` returned or on an outcome string.
  // None of them opened the installed file and looked at line 1 — which is where the only property
  // that decides whether the skill loads at all lives.
  it("starts with the frontmatter fence, so the loader sees a skill", async () => {
    await withTempRepo(async (root) => {
      await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      const written = await readFile(skillPath(root, DEFAULT_SKILL_ROOT), "utf8");
      assert.ok(
        written.startsWith("---\nname: board-process\n"),
        `installed file does not open with frontmatter: ${JSON.stringify(written.slice(0, 60))}`,
      );
    });
  });

  it("still carries the provenance marker, just below the frontmatter", async () => {
    await withTempRepo(async (root) => {
      await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      const lines = (await readFile(skillPath(root, DEFAULT_SKILL_ROOT), "utf8")).split("\n");
      const marker = lines.findIndex((l) => l.includes("dsh-forge skill install"));
      const close = lines.indexOf("---", 1);
      assert.ok(marker > close, "the marker must sit after the closing fence, not inside or above it");
      assert.equal(marker, close + 1, "and immediately after it, so it is not mistaken for prose");
    });
  });

  it("recognises its own output on a second run, wherever the marker sits", async () => {
    // The provenance check is a substring search, so moving the marker must not turn our own file
    // into a foreign one — which would make every reinstall demand --force.
    await withTempRepo(async (root) => {
      await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      const again = await installSkill({ ...ctx, repoRoot: root, skillDirs: [] });
      assert.deepEqual(again.map((r) => r.outcome), ["unchanged"]);

      const path = skillPath(root, DEFAULT_SKILL_ROOT);
      await writeFile(path, `${await readFile(path, "utf8")}\n<!-- a human added a line -->\n`, "utf8");
      const stale = await installSkill({ ...ctx, repoRoot: root, skillDirs: [], dryRun: true });
      assert.deepEqual(stale.map((r) => r.outcome), ["stale"], "ours, edited — not foreign");
    });
  });
});
