/**
 * The board as a page — markdown, for somewhere a person will actually look.
 *
 * `renderColumns` and `renderHierarchy` target a terminal, and reaching them costs a checkout, an
 * authenticated `gh`, and someone who remembers the command exists. That cost is the whole distance
 * between the projection and the complaint it was built for: answering "status ?" should cost a URL.
 * This renders the same snapshot for GitHub, so a scheduled workflow can commit it and the answer is
 * already there when the question occurs to someone.
 *
 * It states no fact of its own. Counts come from `Progress`, membership from `bucketOf`, the epic
 * roll-up from each `EpicNode`'s own progress, the tree from `renderHierarchy` verbatim. A page that
 * decided for itself which items were "moving" would be a second definition of the one word this
 * board exists to make trustworthy.
 *
 * The corollary is that every count on the page has to be over the same population. `buildHierarchy`
 * counts tasks and not the epic issues that contain them, so the sections here do too — see
 * `inBucket`. A header reading "4 running" above a list of ten is not a richer page, it is a page
 * whose reader now has to decide which of its numbers to believe.
 *
 * ## Why there is no "generated at" on the page
 *
 * Because it would be the only thing on it that changes when nothing has happened. Committed every
 * half hour, a moving stamp makes every scheduled run a commit, and the runs where the board
 * actually moved stop being findable among them. So the freshness line states the board's own latest
 * `updatedAt` instead: a fact about the work rather than about when a cron fired, identical across
 * re-renders of the same input, and the more useful of the two — "last activity three days ago" is
 * information, and "generated four minutes ago" is not. When the page is stale because the workflow
 * broke, the file's own commit date says so, which a stamp written by the same broken run could not.
 */

import type { Bucket, EpicNode, Hierarchy, MilestoneNode, Progress } from "./hierarchy.js";
import { bucketOf, progressOf } from "./hierarchy.js";
import type { Anomaly, BoardItem, BoardSnapshot } from "./model.js";
import { compareStrings } from "./order.js";
import { renderBar, renderCompleteness, renderHierarchy, renderProgress } from "./render.js";

/** The comment the workflow's future readers land on when they wonder why their edit vanished. */
const PREAMBLE = "<!-- Generated by `dsh-board digest`. Edits here are overwritten. -->";

/**
 * The most recent `updatedAt` on the board, or `null` for a board with nothing on it.
 *
 * String comparison rather than `Date` parsing: GitHub's timestamps are ISO-8601 in UTC with a fixed
 * width, so they sort lexicographically, and a parse would turn a malformed value into `NaN` — which
 * loses every comparison silently and would report the board as older than it is.
 */
export function latestActivity(items: readonly BoardItem[]): string | null {
  let latest: string | null = null;
  for (const item of items) {
    const at = item.source.updatedAt;
    if (latest === null || at > latest) latest = at;
  }
  return latest;
}

/** `[#159 title](url)` — the identity of an item, as something a phone can tap. */
function link(item: BoardItem): string {
  const id = `${item.source.kind === "pull-request" ? "PR" : "#"}${item.source.number}`;
  return `[${id} ${escapeCell(item.source.title)}](${item.source.url})`;
}

/**
 * Neutralise the two characters that would break out of a table cell.
 *
 * A pipe in an issue title splits the row and shifts every column after it; a newline ends the row
 * outright. Both are legal in a GitHub title, so neither can be assumed away.
 */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

/** The epic slug, or an em-dash, so a table column never renders as an empty cell. */
const epicOf = (item: BoardItem): string => (item.epic === null ? "—" : `\`${item.epic}\``);

const phaseOf = (item: BoardItem): string =>
  item.phase === null ? "—" : `\`${item.phase.name}\``;

/** Items as a three-column table. Empty in, empty out — the caller decides what that means. */
function table(items: readonly BoardItem[]): readonly string[] {
  if (items.length === 0) return [];
  return [
    "| item | column | epic |",
    "| --- | --- | --- |",
    ...items.map((i) => `| ${link(i)} | ${phaseOf(i)} | ${epicOf(i)} |`),
    "",
  ];
}

/**
 * One headed table of items, or nothing at all.
 *
 * An empty section renders as no section rather than as a heading over a blank space. A page with a
 * standing "Stuck" heading trains its reader to skip that heading, which is the one outcome a page
 * about what needs attention cannot afford.
 */
function section(title: string, blurb: string, items: readonly BoardItem[]): readonly string[] {
  if (items.length === 0) return [];
  return [`## ${title} (${items.length})`, "", blurb, "", ...table(items)];
}

/** The same table, folded away. For the sections that describe shape rather than urgency. */
function collapsed(title: string, summary: string, body: readonly string[]): readonly string[] {
  if (body.length === 0) return [];
  return [`## ${title}`, "", "<details>", `<summary>${summary}</summary>`, "", ...body, "</details>", ""];
}

/** A bar and the words for the same numbers, as one cell. */
const progressCell = (progress: Progress): string =>
  `\`${renderBar(progress, 12)}\` ${renderProgress(progress)}`;

/** One epic as a table row: where it stands, and how far its tasks have got. */
function epicRow(epic: EpicNode): string {
  const name =
    epic.issue === null
      ? `${escapeCell(epic.title)} _(no issue claims \`${epic.slug}\`)_`
      : `[${escapeCell(epic.title)}](${epic.issue.source.url})`;
  const phase = epic.issue?.phase?.name ?? "no status";
  return `| ${name} | ${progressCell(epic.progress)} | \`${phase}\` |`;
}

/**
 * The milestone → epic roll-up: where the project stands, one line per epic.
 *
 * This is the view the terminal tree gives only after it is expanded and read. Every number in it
 * is an `EpicNode`'s own `progress`, computed once by `buildHierarchy` — the page adds none.
 *
 * The tasks in a milestone that claim no epic get a row of their own, because the milestone's own
 * total counts them: without it, a milestone reading 29/38 sits over rows adding to 1/1, and the
 * reader has no way to tell whether the missing 37 are hidden or miscounted.
 */
function epicSections(milestones: readonly MilestoneNode[]): readonly string[] {
  const lines: string[] = [];
  for (const milestone of milestones) {
    // A milestone with no epics has nothing to say in an epic roll-up, whatever else is filed in
    // it. Its items are still listed by the sections above and drawn in the tree below.
    if (milestone.epics.length === 0) continue;
    const loose = milestone.looseTasks;
    lines.push(
      // The milestone name carries its own dash often enough that appending the progress after
      // another one reads as a single run-on title. Its own line, under the heading.
      `### ${milestone.name ?? "(no milestone)"}`,
      "",
      progressCell(milestone.progress),
      "",
      "| epic | progress | column |",
      "| --- | --- | --- |",
      ...milestone.epics.map(epicRow),
      ...(loose.length === 0
        ? []
        : [`| _(no epic)_ | ${progressCell(progressOf(loose))} | — |`]),
      "",
    );
  }
  if (lines.length === 0) return [];
  return ["## Epics", "", ...lines];
}

function anomalyLines(anomalies: readonly Anomaly[]): readonly string[] {
  const byKind = new Map<string, string[]>();
  for (const anomaly of anomalies) {
    const where = anomaly.item === null ? "" : `**#${anomaly.item}** — `;
    const list = byKind.get(anomaly.kind);
    if (list === undefined) byKind.set(anomaly.kind, [`- ${where}${anomaly.detail}`]);
    else list.push(`- ${where}${anomaly.detail}`);
  }
  const lines: string[] = [];
  for (const kind of [...byKind.keys()].sort(compareStrings)) {
    lines.push(`**\`${kind}\`**`, "");
    lines.push(...(byKind.get(kind) ?? []));
    lines.push("");
  }
  return lines;
}

/**
 * Render the whole page.
 *
 * Takes both the snapshot and the hierarchy built from it, rather than building the hierarchy here,
 * so that the page is a pure function of what the caller already has and the CLI keeps deciding when
 * work happens.
 */
export function renderDigest(snapshot: BoardSnapshot, hierarchy: Hierarchy): string {
  // Tasks only, because the ratio in the header is `Progress`, and `buildHierarchy` deliberately
  // leaves epic issues out of it — an epic that counted itself would make every board look busier
  // than it is. A section that counted them would then head a list of ten under a line that says
  // four, and a reader who has to reconcile two numbers on one page trusts neither. Epics are not
  // lost by this: they get their own roll-up below, which is the more useful view of them anyway.
  const inBucket = (name: Bucket): readonly BoardItem[] =>
    snapshot.items.filter((i) => !i.isEpic && bucketOf(i) === name);

  // `invisible` covers closed items too, and a closed item with no status label is either the
  // correct shape for abandoned work or already named under `closed-without-status` below. Nagging
  // about it here would put the prescribed ending on a list headed "needs attention".
  const unlabelled = inBucket("invisible").filter((i) => i.source.state === "open");

  const activity = latestActivity(snapshot.items);
  const banner = renderCompleteness(snapshot.completeness);

  const lines: string[] = [
    PREAMBLE,
    "",
    `# ${snapshot.repo}`,
    "",
    `\`${renderBar(hierarchy.progress)}\` **${renderProgress(hierarchy.progress)}**`,
    "",
  ];

  if (banner !== null) lines.push(`> ${banner}`, "");

  lines.push(
    activity === null
      ? "_Nothing on the board yet._"
      : `_Latest board activity: ${activity}._ Projected from GitHub, which is the truth — where` +
          " this page and an issue disagree, the issue wins.",
    "",
  );

  lines.push(
    ...section(
      "Moving now",
      "Something could be acting on these right now.",
      inBucket("inFlight"),
    ),
    ...section("Stuck", "Not moving, and not waiting on anything that will start on its own.", inBucket("blocked")),
    ...section(
      "Not on the board",
      "Open, and carrying no `status:` label — real work no column can see.",
      unlabelled,
    ),
  );

  if (snapshot.anomalies.length > 0) {
    lines.push(
      `## Anomalies (${snapshot.anomalies.length})`,
      "",
      "`dsh-board check` fails on these. The board contradicts itself until they are repaired, and" +
        " it is repaired on the issue, never here.",
      "",
      ...anomalyLines(snapshot.anomalies),
    );
  }

  // Below the anomalies, deliberately: a roll-up read over a board that contradicts itself is a
  // roll-up of the wrong numbers, and the warning has to come first to say so.
  lines.push(...epicSections(hierarchy.milestones));

  const queued = inBucket("queued");
  lines.push(
    ...collapsed("Waiting to start", `${queued.length} filed, nothing started`, table(queued)),
  );

  lines.push(
    ...collapsed("The tree", "milestone → epic → task", [
      "```",
      // No stamp: see the header comment. The freshness line above already carries the only
      // timestamp on this page, and it is one that means something.
      //
      // No anomaly banner either, and this is the only view entitled to leave it out: `## Anomalies`
      // above states the same count with the detail and the repair beside it, which is strictly
      // more than the banner says. A terminal view has no such section, which is why the option
      // defaults the other way.
      renderHierarchy(hierarchy, { stamp: false, anomalies: false }),
      "```",
      "",
    ]),
  );

  lines.push("---", "", "Run `dsh-board status` for this tree in a terminal, or `dsh-board check` to fail on the anomalies.");

  return `${lines.join("\n")}\n`;
}
