import { integers, isRecord, records } from '../json.ts';

/** First line of every generated status page: names the generator, which is the only writer. */
export const STATUS_PROVENANCE = '<!-- Generated by packages/method (harness-method milestone render). Do not edit. -->';

export interface MilestoneClusterStateView {
  readonly milestone?: unknown;
  readonly updatedAt?: unknown;
  readonly currentMainSha?: unknown;
  readonly lanes?: unknown;
  readonly leaves?: unknown;
  readonly expensiveGates?: unknown;
  readonly canaryCheckpoints?: unknown;
  readonly reporting?: unknown;
  readonly releaseCaptain?: unknown;
}

function stableValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stableValue);
  if (!isRecord(value)) return value;
  return Object.fromEntries(
    Object.keys(value).sort().map((key) => [key, stableValue(value[key])]),
  );
}

export async function stateDigest(state: unknown): Promise<string> {
  const bytes = new TextEncoder().encode(JSON.stringify(stableValue(state)));
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

function text(value: unknown, fallback = '—'): string {
  return typeof value === 'string' && value.length > 0 ? value : fallback;
}

function cell(value: unknown, fallback = '—'): string {
  return text(value, fallback).replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function itemList(value: unknown): string {
  if (!Array.isArray(value) || value.length === 0) return '—';
  return value.map((entry) => typeof entry === 'number' ? `#${entry}` : cell(entry)).join(', ');
}

export async function renderMilestoneStatus(state: MilestoneClusterStateView): Promise<string> {
  const digest = await stateDigest(state);
  const lanes = records(state.lanes);
  const leaves = records(state.leaves);
  const gates = records(state.expensiveGates);
  const checkpoints = records(state.canaryCheckpoints);
  const reporting = isRecord(state.reporting) ? state.reporting : null;
  const captain = isRecord(state.releaseCaptain) ? state.releaseCaptain : {};

  const lines = [
    STATUS_PROVENANCE,
    `<!-- milestone-cluster-state-sha256: ${digest} -->`,
    '',
    `# Milestone ${text(state.milestone)} cluster status`,
    '',
    `- Updated: ${text(state.updatedAt)}`,
    `- Current main: \`${text(state.currentMainSha)}\``,
    `- Release captain: ${text(captain.state, 'inactive')}`,
  ];

  if (reporting) {
    const canary = isRecord(reporting.canary) ? reporting.canary : {};
    const eta = isRecord(canary.eta) ? canary.eta : {};
    const progress = isRecord(reporting.progress) ? reporting.progress : {};
    const scope = isRecord(reporting.scope) ? reporting.scope : {};
    const environment = isRecord(reporting.environment) ? reporting.environment : {};
    const criticalPath = records(canary.criticalPath);
    const mergeQueue = records(reporting.mergeQueue);
    const blockers = records(reporting.blockers);
    const matrix = records(reporting.orchestratorMatrix);
    const decisions = records(reporting.ownerDecisions);

    lines.push(
      '',
      '## Outcome',
      '',
      `${cell(reporting.headline)}`,
      '',
      `- Reported: ${text(reporting.lastReportAt)}`,
      `- Next heartbeat due: ${text(reporting.nextReportDueAt)}`,
      `- Evidence record: ${text(reporting.lastReportRef)}`,
      '',
      '## Canary / release path',
      '',
      `- Target: ${cell(canary.target)}`,
      `- State: ${cell(canary.state)}`,
      `- ETA: ${cell(eta.window)} (${cell(eta.confidence)} confidence)`,
      `- Basis: ${cell(eta.basis)}`,
      '',
    );
    if (criticalPath.length === 0) {
      lines.push('_No critical path is currently declared._');
    } else {
      lines.push(
        '| Order | Item | State | Release impact | Next action |',
        '| ---: | --- | --- | --- | --- |',
      );
      criticalPath.forEach((item, index) => {
        lines.push(
          `| ${index + 1} | ${cell(item.id)} | ${cell(item.state)} | ${cell(item.impact)} | ${
            cell(item.nextAction)
          } |`,
        );
      });
    }

    lines.push(
      '',
      '## Progress since previous report',
      '',
      `- Merged PRs: ${itemList(progress.mergedPullRequests)}`,
      `- Closed issues: ${itemList(progress.closedIssues)}`,
      `- New intake: ${itemList(progress.newIssues)}`,
      `- Queue delta: ${cell(progress.queueDeltaExplanation)}`,
      '',
      '## Next merge queue',
      '',
    );
    if (mergeQueue.length === 0) {
      lines.push('_No near-term merge candidate is declared._');
    } else {
      lines.push(
        '| PR | Lane | Evidence state | Remaining gate | Next action |',
        '| --- | --- | --- | --- | --- |',
      );
      for (const candidate of mergeQueue) {
        const pr = typeof candidate.prNumber === 'number' ? `#${candidate.prNumber}` : '—';
        lines.push(
          `| ${pr} | ${cell(candidate.lane)} | ${cell(candidate.state)} | ${
            cell(candidate.nextGate)
          } | ${cell(candidate.nextAction)} |`,
        );
      }
    }

    lines.push('', '## Current blockers', '');
    if (blockers.length === 0) {
      lines.push('_No current blocker._');
    } else {
      lines.push(
        '| ID | Class | Plain-English red | Impact | Owner | Next action | Owner decision |',
        '| --- | --- | --- | --- | --- | --- | --- |',
      );
      for (const blocker of blockers) {
        lines.push(
          `| ${cell(blocker.id)} | ${cell(blocker.category)} | ${cell(blocker.summary)} | ${
            cell(blocker.impact)
          } | ${cell(blocker.owner)} | ${cell(blocker.nextAction)} | ${
            blocker.ownerDecisionRequired === true ? 'yes' : 'no'
          } |`,
        );
      }
    }

    lines.push(
      '',
      '## Orchestrator matrix',
      '',
      '| Lane | State | Active items | Last concrete progress | Blocker | Next action |',
      '| --- | --- | --- | --- | --- | --- |',
    );
    for (const row of matrix) {
      lines.push(
        `| ${cell(row.lane)} | ${cell(row.state)} | ${itemList(row.activeItems)} | ${
          cell(row.lastConcreteProgressAt)
        } | ${cell(row.blocker)} | ${cell(row.nextAction)} |`,
      );
    }

    lines.push(
      '',
      '## Scope coverage',
      '',
      `- Open issues: ${String(scope.openIssueCount ?? '—')}`,
      `- Owned issues: ${String(scope.ownedIssueCount ?? '—')}`,
      `- Scheduled issues: ${String(scope.scheduledIssueCount ?? '—')}`,
      `- Unscheduled issues: ${itemList(integers(scope.unscheduledIssueNumbers))}`,
      `- Open PRs: ${String(scope.openPullRequestCount ?? '—')}`,
      '',
      '## Environment hygiene',
      '',
      `- Checked: ${cell(environment.checkedAt)}`,
      `- Aspire applications: ${String(environment.aspireApplications ?? 'unknown')}`,
      `- Docker containers: ${String(environment.dockerContainers ?? 'unknown')}`,
      `- Docker custom networks: ${String(environment.dockerCustomNetworks ?? 'unknown')}`,
      '',
      '## Owner decisions',
      '',
    );
    if (decisions.length === 0) {
      lines.push('_No owner decision needed._');
    } else {
      lines.push('| ID | Question | Why owner-only | Blocked items |', '| --- | --- | --- | --- |');
      for (const decision of decisions) {
        lines.push(
          `| ${cell(decision.id)} | ${cell(decision.question)} | ${cell(decision.whyOwnerOnly)} | ${
            itemList(decision.blockedItems)
          } |`,
        );
      }
    }
  }

  lines.push(
    '',
    '## Topic lanes',
    '',
    '| Lane | Orchestrator | Issues | Active implementation | Active evaluation |',
    '| --- | --- | ---: | ---: | ---: |',
  );

  for (const lane of lanes) {
    const laneId = text(lane.id);
    const issueCount = Array.isArray(lane.issueNumbers) ? lane.issueNumbers.length : 0;
    const laneLeaves = leaves.filter((leaf) => leaf.lane === lane.id);
    const implementationCount = laneLeaves.filter((leaf) =>
      leaf.phase === 'implementing' || leaf.phase === 'gating'
    ).length;
    const evaluationCount = laneLeaves.filter((leaf) => leaf.phase === 'evaluating').length;
    lines.push(
      `| ${laneId} | ${
        text(lane.orchestratorAgentId)
      } | ${issueCount} | ${implementationCount} | ${evaluationCount} |`,
    );
  }

  lines.push('', '## Leaves', '');
  if (leaves.length === 0) {
    lines.push('_No leaf PRs dispatched._');
  } else {
    lines.push('| PR | Lane | Phase | Head | Blocker |', '| --- | --- | --- | --- | --- |');
    for (const leaf of leaves) {
      const pr = typeof leaf.prNumber === 'number' ? `#${leaf.prNumber}` : '—';
      lines.push(
        `| ${pr} | ${text(leaf.lane)} | ${text(leaf.phase)} | \`${text(leaf.headSha)}\` | ${
          text(leaf.blocker)
        } |`,
      );
    }
  }

  const runningGates = gates.filter((gate) => gate.state === 'running').length;
  lines.push(
    '',
    '## Release train',
    '',
    `- Global expensive gates running: ${runningGates}`,
    `- Canary checkpoints: ${checkpoints.length}`,
    `- Release writer: ${text(captain.agentId)}`,
    '',
  );
  return `${lines.join('\n')}\n`;
}
